### ISSUE TITLE
customize output

### ISSUE THREAD

**Issue by warengonzaga** [hoshiyuki-tamako/file-split-to-directory#10]
I have few things in my mind, customization for output.

- custom output folder names
  - instead of 0, 1, 2, can be do like "Batch 1, Batch 2, Batch 3"
- custom output directory where the split happens
  - for example, I want to specify the path where the folders show up.

Just some ideas, I can do all of this manually with FS in node.js maybe useful as an upgrade in the future.

Adding your project to my projects, will wait for updates.

**Comment by hoshiyuki-tamako** [comment]
Added both features on version 2.2.0 and pushed to npm


```ts
const fstd = new FileSplitToDirectory();
fstd.directoryNameGenerator = (i: number) => i.toString();
fstd.runSync('D:/download', 100, 'E:/processed');
```

**Comment by warengonzaga** [comment]
> Added both features on version 2.2.0 and pushed to npm
> 
> ```ts
> const fstd = new FileSplitToDirectory();
> fstd.directoryNameGenerator = (i: number) => i.toString();
> fstd.runSync('D:/download', 100, 'E:/processed');
> ```

That was quick! How do you use the other one? For example "Batch 1"
`fstd.directoryNameGenerator = (i: number) => i.toString();`

**Comment by hoshiyuki-tamako** [comment]
```ts
// i=0, i=1, i=2, i=...
// Batch 1, Batch 2, Batch 3, ...
fstd.directoryNameGenerator = (i) => `Batch ${i + 1}`;
```

**Comment by warengonzaga** [comment]
> ```ts
> // i=0, i=1, i=2, i=...
> // Batch 1, Batch 2, Batch 3, ...
> fstd.directoryNameGenerator = (i) => `Batch ${i + 1}`;
> ```

Updating the latest version, checking this.

**Comment by warengonzaga** [comment]
Works like a charm, I noticed that it does move the files to the output folder. Maybe good to have an option for moving or copying the files. Instead of moving only. All good! Thanks for the quick updates!
