### ISSUE TITLE
not sorted corrected

### ISSUE THREAD

**Issue by warengonzaga** [hoshiyuki-tamako/file-split-to-directory#9]
Yes, it creates folder based on how many you want inside, but it is not arranged in order.
![image](https://user-images.githubusercontent.com/15052701/214247935-86910237-9384-4070-b471-994e1fa5c5a5.png)

I'm adding a create batch functionality with my art engine.

**Comment by hoshiyuki-tamako** [comment]
I had added natural sort using Intl.Collator for filenames and it should be working now, please try update to 2.1.0

npm -g install file-split-to-directory@2.1.0
npm install file-split-to-directory@2.1.0

Thanks for the bug report

**Comment by warengonzaga** [comment]
Hey @hoshiyuki-tamako let me take a look and get back to you.

**Comment by warengonzaga** [comment]
Hey @hoshiyuki-tamako works like a charm! Closing the issue now.
